sudo: required
language: ruby
rvm:
- 2.4
- ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
services:
- postgresql
- docker

env:
  global:
  - DATABASE_HOST=localhost
  - APP_PORT=80
  - APP_LOG_DIR=`pwd`/app/log
  - secure: jLu4qx604gcjEvRxBg1vvYmW0UUynljm3zn5ReRkdqmMEqxDpr3ycVAvZtGwc+ynoqacloHZHbzhzv8K9Qplne8RIrYqzSHbjSdVBHtl1IxMFd1NhXYskXTuIa8yq7JXqn9XtukJR9S4aIb9FFLbuf0M7MJTBiaktF/ENy+9ZbumZq06yWwLKrEKgtzU7ZZf0KFjetpZdMZ/stnNDRQS8gotrvF52o+iamIze2QaE7l0KObI91svQSFg2xODLUKm5Vo8iZ+XxY1RR2O8fy6Ge+jhaABCtYDbzDLW/WYTNprou9kovzPl7z4cYBTUJcbeKzB6erACnRrsLV3by2CSuThHcHCKN7CPH7lgqix5c7VnUmt0hgjajq8iEBsiVRcK5PQYujhjl5f3LsxJqo1KmcXtP+tAsnUW0VSEjlDpPCcTn2Rhc1TiX2Yp1zFxr50ryi9OUPNPjFL80zz8xzcyzyJtqOxZcnBdUMVz1fyU9Iu+Rz6Ac22M8CRVM1YOm7ftY86E4HrrieQCA7T3uVh2ZiF8z1dyfIM/DhDleSkVrHNmorTBRExDb6K8kYGpOgF39u9ZUwRI6h3wPp9CtuhAOSB+fE7IvDHDsbxAXFd6H2ksmbaBqEVT2uPa8iPKBYdQw5070WsmjNsuKp7V/okgvYjzBvKU/m+jgbbACt9+Hgo=
  - secure: VJc4Y+VYLbmU9wCPD4x4QUZMsXKG/wI+iTf1gh8unXg1El4ZVFfdMW3gX/WL86ANQWx6/TeDFGDdDdkItYK8XQInohe7H1QzLPFjRYvterJKUtDR5dXDH2CyYkb9USMsK/JuYrGhljl7Q1qBoRKscLhMuaeOVzJhZvLCnA7EoZQapIj8AnfdlT+Mh97CHYPjiw7UIpf9nWDB40wFFiPj+qlWiAIYJJRWZwph6Ni9G/7tQqcGiT7rnJtOrfBzOtCyySdf4ve0FCM87DKQeE07rbRjsmezPfwQ9VKDPJNq86vYJSZJzcapdUObCd4nIBUExyBg9k/pt5MBG0W0W3gSQ7xzDbkMMMuCJ5T2wbuX8Z80cpNHracz/j6pc7fGjuojOvP/tBVfZGyVWJdM4xTPFhAX9GZIzr6PX0U8l13HjT+kbnw9e7Shfeb7CFcpj4WuzRxcT+fFRYZMxqdwC/4a3WQeR6hdVpZ45ug5qa/QEy5wEEtWZwfX4U+VCgk7RAe3hhZeXZl45o/FCXVd5DlPSJK31PCOc4Er4HpVQoDSeFahxPWqHEPCZLkaW1Jwz0NwBu82tpRwJcTY1cK72VAZB5qFbe0gh580LWSAI2aYrKv3LjuCidfZp7Tm77s7AsAaagwSWnAG7BA3RaKJT7NpGJ4vcEeMC2Ik5JWJciPfGg4=
  - secure: ftSh5forKNU7xTy3H86kjJRqK77o38B8RXnEDeY44tdq0fM9LXDIKDfnydwPpcVdPon8NL/3IP+w6h3Z4cDFQznI82AzFdB0aTmDS0XU871MIel8dnB+FhGjeeUYMG8/SN1nxlG1Xo3epbuIuA+I8w4BH9chOIkLcsjtZqnhJ24r6xDpC6WiuzRM7zZbSvXS9TXg+rmGBM/4JzN1lhRX3cYfloJ1y/wICVL8XR+MYO+F29adsLWtVJ7kQ1Ers8jeBQbVxdR+4hQMhWPEVoMfqUcUp27RdZjxH9KK1VO6ZATkezJxTQOCm3db74NiAncnZZci+nKR0qNuEi2Io0Mr4wBjNv2KANsqrplQrNMVJ4DylN0qe8Zb+QUTgRpnxAHvbJgyXYPrzdD3TEmBzKXtZahZPSzXukgC/L3euDj2viX4Nby6jmmsR2d1UyLJhHgmTnlcZfC/Cdf0MwchjrrfrZWaGJWWO3PnWNCEUA3R/7S8gjTXm7b/E60JJq9j384jPMlB6lb5wKITzvasEARqjwa1cQjkyFthFkpGzZUt0K/qSROVJyWEbzkC542qnG4/m+JeU3CcJIfOIKtWey+baucTNkKT7FNf1xxZB9JkTeERWV0tqYjqQN050DdESts1E5dwA1VTO4sim1RnfBuBu38vGiRSrHxDrP4yOuj6VXI=
before_install:
- psql -f ./db/container-files/docker-entrypoint-initdb.d/db.sql -U postgres
- cd ./app
before_script:
- mkdir ./log
script: ./bin/run-tests
after_success:
- test $TRAVIS_RUBY_VERSION == "2.4" && git clean -xfd && ../bin/docker-push ihsw/omega-jazz
