sudo: false
language: ruby
rvm:
  - 2.3.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
services:
  - postgresql

env:
  - DATBASE_HOST=localhost
before_install:
  - psql -f ./db/container-files/docker-entrypoint-initdb.d/db.sql -U postgres
  - cd ./app
