sudo: false
language: ruby
rvm:
  - 2.2.3
  - ruby-head
services:
  - postgresql

env:
  - ENV=travis
before_install:
  - cd ./app
before_script:
  - psql -f ./db/container-files/docker-entrypoint-initdb.d/db.sql -U postgres
