base:
  image: ihsw/omega-jazz
web-test:
  extends:
    service: base
web:
  extends:
    service: base
  ports:
    - 80:80
web-dev:
  extends:
    service: base
  ports:
    - 80:80
  volumes:
    - ./app:/srv/app
test:
  extends:
    service: base
  command: bundle exec rake
test-dev:
  extends:
    service: test
  volumes:
    - ./app:/srv/app
