db:
  image: ihsw/omega-jazz-db

base:
  image: ihsw/omega-jazz
  environment:
    - ENV=local
test-base:
  extends:
    service: base
  command: ./bin/run-tests

web-test:
  extends:
    service: base
  links:
    - db

web:
  extends:
    service: base
  ports:
    - 80:80
  links:
    - db
web-dev:
  extends:
    service: base
  ports:
    - 80:80
  volumes:
    - ./app:/srv/app
  links:
    - db

test:
  extends:
    service: test-base
  links:
    - db
test-dev:
  extends:
    service: test-base
  volumes:
    - ./app:/srv/app
  links:
    - db
