db:
  image: ihsw/omega-jazz-db

base:
  image: ihsw/omega-jazz
  environment:
    - DATABASE_HOST=Db
test-base:
  extends:
    service: base
  command: ./bin/run-tests

test:
  extends:
    service: test-base
  links:
    - db:Db
test-dev:
  extends:
    service: test-base
  links:
    - db:Db
  volumes:
    - ./app:/srv/app
