source 'https://rubygems.org'

gem 'sinatra'
gem 'activerecord'
gem 'pg', '~> 0.20'
gem 'bcrypt'
gem 'warden'

group :test do
  gem 'rake'
  gem 'minitest'
  gem 'rack-test'
  gem 'coveralls', :require => false
end
